version: '3'
services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_DB: testprisma
      POSTGRES_USER: root
      POSTGRES_PASSWORD: '12345678'
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  node-server:
    restart: always
    build: 
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on: 
      db:
        condition: service_healthy
        restart: true



volumes:
  postgres-data:

networks:
  my-network:
