name: CI

env:
  NODE_VERSION: "21.x"
  FOLDER: ~/applications/prisma-test
  IMAGE: brightky/prisma-test
  IMAGE_VERSION: latest
  DOCKER_NETWORK_NAME: myNet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clean-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clean postgres
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker kill db || true
            docker rm -f db || true
      - name: Clean postgres
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker kill app || true
            docker rm -f app || true
  create-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf ${{ env.FOLDER }}
            mkdir -p  ${{ env.FOLDER }}
            chmod ugo+rwx  ${{ env.FOLDER }}

  create-docker-network:
    runs-on: ubuntu-latest
    steps:
      - name: create docker network
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker network rm ${{ env.DOCKER_NETWORK_NAME }} ; true
            docker network create ${{ env.DOCKER_NETWORK_NAME }} --driver bridge ; true

  init-postgres:
    runs-on: ubuntu-latest
    needs: [clean-docker, create-docker-network]
    steps:
      - name: Initialize PostgreSQL
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker run -d -p 5432:5432 --name db -e POSTGRES_PASSWORD=12345678 -e POSTGRES_USER=root -e POSTGRES_DB=root postgres:latest
            docker network connect ${{ env.DOCKER_NETWORK_NAME }} db

  copy-files:
    runs-on: ubuntu-latest
    needs: [create-folder]
    steps:
      - uses: actions/checkout@v4
      - name: copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "*"
          target: ${{ env.FOLDER }}

  dockerize:
    runs-on: ubuntu-latest
    needs: [copy-files, init-postgres]
    steps:
      - name: dockerize
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.FOLDER }}
            docker build -t ${{ env.IMAGE }}:${{ env.IMAGE_VERSION }} .
  build-app:
    runs-on: ubuntu-latest
    needs: [dockerize]
    steps:
      - name: build app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker run -d -p 3000:3000 --name app -t ${{ env.IMAGE }}:${{ env.IMAGE_VERSION }} 'sh'
            docker network connect ${{ env.DOCKER_NETWORK_NAME }} app || true

  run-app:
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: run app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker exec -d ${{ env.IMAGE }}:${{ env.IMAGE_VERSION }} 'npx prisma migrate dev --name init'
            docker exec -d ${{ env.IMAGE }}:${{ env.IMAGE_VERSION }} 'npx prisma generate'
            docker exec -d ${{ env.IMAGE }}:${{ env.IMAGE_VERSION }} 'npm run start'
            
